# Generated by Django 5.0.7 on 2024-07-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_comment_field_productrating_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='star_rating',
            field=models.PositiveSmallIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)]),
        ),
    ]
