# Generated by Django 5.0.7 on 2024-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productrating_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='star_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
