# Generated by Django 5.0.7 on 2024-07-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_items',
            field=models.ManyToManyField(through='products.OrderItem', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order'),
        ),
    ]
