# Generated by Django 5.0.7 on 2024-07-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
